import { readdir, readFile } from "node:fs/promises";
import { describe, expect, it } from "vitest";
import { disclosureApprovalSubjectDigest, disclosureBindingDigest, disclosureCatalogDigest, requiredDisclosureCategories, resolveDisclosures, validateDisclosureCatalogIntegrity, type DisclosureApproval, type DisclosureCatalog, type DisclosureEntry, type DisclosureRequest } from "../../src/domain/disclosure-catalog.js";
import { draftDisclosureCatalog } from "../../src/infrastructure/disclosures/draft-disclosure-catalog.js";

const now = new Date("2026-08-10T00:00:00.000Z"); const sha = "a".repeat(64); const lifecycle = { effectiveFrom: "2026-08-01T00:00:00.000Z", reviewBy: "2026-09-01T00:00:00.000Z", supportedUntil: "2026-10-01T00:00:00.000Z" };
const target = { audience: "operator", channel: "cli", timing: "before-confirmation", severity: "warning", trigger: "package-acquisition", outcome: "planned-change" } as const;
const binding = { operation: "package-acquisition", provider: "homebrew", providerRole: "primary", capabilityId: "homebrew-formula", sideEffect: "package-install", privilege: "user", network: "required", confirmation: "required", rollback: "manual", reassessment: "required" } as const;
const approvals: readonly DisclosureApproval[] = [{ role: "security", reviewer: "identity:security", decision: "approved", decidedAt: "2026-08-02T00:00:00.000Z", subjectDigest: sha, signoffRef: `sha256:${sha}` }, { role: "ux-comprehension", reviewer: "identity:ux", decision: "approved", decidedAt: "2026-08-02T00:00:00.000Z", subjectDigest: sha, signoffRef: `sha256:${sha}` }];
const rawRequest = (): DisclosureRequest => ({ target, binding, instance: { requestId: "request:one", planId: "plan:one", planExpiresAt: "2026-08-20T00:00:00.000Z", bindingDigest: sha, confirmation: { id: "confirmation:one", requestId: "request:one", planId: "plan:one", bindingDigest: sha, decision: "accepted", expiresAt: "2026-08-19T00:00:00.000Z", consumed: false }, presentation: { id: "presentation:one", requestId: "request:one", planId: "plan:one", confirmationId: "confirmation:one", replayId: "replay:one", freshUntil: "2026-08-18T00:00:00.000Z", consumed: false } }, requiredCategories: [...requiredDisclosureCategories], consumedReplayIds: [], values: {} });
async function request(change: Partial<DisclosureRequest> = {}) { const candidate = { ...rawRequest(), ...change }; const digest = await disclosureBindingDigest(candidate); return { ...candidate, instance: { ...candidate.instance, bindingDigest: digest, confirmation: { ...candidate.instance.confirmation, bindingDigest: digest } } }; }
const entry = (category: DisclosureEntry["target"]["category"], bindingDigest: string, change: Partial<DisclosureEntry> = {}): DisclosureEntry => ({ id: `disclosure:${category}`, version: "1.0.0", status: "approved", owner: "identity:owner", preparer: "identity:preparer", approvals, provenance: { repository: "https://example.test/repo", commitSha: sha, artifactSha256: sha, fixture: false }, lifecycle, supersedes: [], supersededBy: "", conflictsWith: [], ambiguous: false, target: { ...target, category }, binding, bindingDigest, template: `Review {{subject}} for ${category}.`, placeholders: [{ name: "subject", classification: "sensitive", redactionPolicyDigest: sha }], locale: "en-US", accessibility: "plain-text", comprehension: "external-review-required", fallback: "refuse", supportRef: "support:workstation", privacy: { classification: "internal", redactionPolicyDigest: sha, retention: "ephemeral", maxTemplateBytes: 100 }, ...change });
async function signed(candidateRequest?: DisclosureRequest, entries?: readonly DisclosureEntry[], change: Partial<DisclosureCatalog> = {}) { candidateRequest ??= await request(); const bind = async (subject: unknown, candidates: readonly DisclosureApproval[]) => { const subjectDigest = await disclosureApprovalSubjectDigest(subject); return candidates.map((approval) => ({ ...approval, subjectDigest })); }; const candidates = entries ?? requiredDisclosureCategories.map((category) => entry(category, candidateRequest.instance.bindingDigest)); const bound = await Promise.all(candidates.map(async (item) => ({ ...item, approvals: await bind(item, item.approvals) }))); const catalog: DisclosureCatalog = { schemaVersion: "DisclosureCatalogV1", id: "catalog:synthetic", version: "1.0.0", status: "approved", owner: "identity:catalog-owner", preparer: "identity:catalog-preparer", requiredApprovals: ["security", "ux-comprehension"], approvals, provenance: { repository: "https://example.test/repo", commitSha: sha, artifactSha256: sha, fixture: false }, lifecycle, requiredCategories: [...requiredDisclosureCategories], entries: bound, digest: "", ...change }; const approved = { ...catalog, approvals: await bind(catalog, catalog.approvals) }; return { ...approved, digest: await disclosureCatalogDigest(approved) }; }
const eligible = async (catalog: DisclosureCatalog, candidate?: DisclosureRequest, date = now) => resolveDisclosures(catalog, candidate ?? await request(), date);

describe("structural disclosure catalog", () => {
  it("ships an integrity-valid empty unapproved draft", async () => { expect(await validateDisclosureCatalogIntegrity(draftDisclosureCatalog)).toBe(true); expect(await eligible(draftDisclosureCatalog)).toMatchObject({ available: false, structurallyEligible: false, reason: "catalog-not-approved", authority: "none" }); });
  it("terminates synthetic structural eligibility at independent copy review without returning entries or copy", async () => { const candidate = await request(); const result = await eligible(await signed(candidate), candidate); expect(result).toMatchObject({ available: false, structurallyEligible: true, reason: "independent-copy-review-required", authority: "none", copyApproval: "not-established", bindingDigest: candidate.instance.bindingDigest }); expect(result).not.toHaveProperty("entries"); expect(JSON.stringify(result)).not.toMatch(/template|Review/); if (!result.structurallyEligible) throw new Error("expected structural terminal"); expect(Object.isFrozen(result) && Object.isFrozen(result.entryIds) && Object.isFrozen(result.entrySubjectDigests)).toBe(true); });
  it.each([["empty", []], ["incomplete", requiredDisclosureCategories.slice(0, -1)], ["duplicate", [...requiredDisclosureCategories.slice(0, -1), "operation"]], ["irrelevant", [...requiredDisclosureCategories.slice(0, -1), "other"]]] as const)("rejects %s governed categories", async (_name, categories) => { const candidate = await request({ requiredCategories: categories as DisclosureRequest["requiredCategories"] }); expect((await eligible(await signed(), candidate)).structurallyEligible).toBe(false); });
  it("requires complete unique catalog coverage", async () => { const candidate = await request(); const complete = requiredDisclosureCategories.map((category) => entry(category, candidate.instance.bindingDigest)); expect((await eligible(await signed(candidate, complete.slice(0, -1)), candidate)).structurallyEligible).toBe(false); expect((await eligible(await signed(candidate, [...complete.slice(0, -1), entry("operation", candidate.instance.bindingDigest, { id: "disclosure:other" })]), candidate)).structurallyEligible).toBe(false); });
  it("rejects arbitrary and caller-recomputed bindings", async () => { const candidate = await request(); const catalog = await signed(candidate); const arbitrary = { ...candidate, instance: { ...candidate.instance, bindingDigest: sha, confirmation: { ...candidate.instance.confirmation, bindingDigest: sha } } }; expect((await eligible(catalog, arbitrary)).structurallyEligible).toBe(false); const changed = await request({ binding: { ...binding, privilege: "elevated" } }); expect((await eligible(catalog, changed)).structurallyEligible).toBe(false); });
  it.each([["trigger", { target: { ...target, trigger: "configuration-apply" } }], ["operation", { binding: { ...binding, operation: "configuration-apply" } }], ["side effect", { binding: { ...binding, sideEffect: "configuration-write" } }], ["outcome", { target: { ...target, outcome: "reassessment-required" }, binding: { ...binding, reassessment: "none" } }]] as const)("rejects closed relationship mismatch: %s", async (_name, change) => { const candidate = await request(change as Partial<DisclosureRequest>); expect((await eligible(await signed(), candidate)).structurallyEligible).toBe(false); });
  it("rejects future approvals", async () => { const candidate = await request(); const future = requiredDisclosureCategories.map((category) => entry(category, candidate.instance.bindingDigest, { approvals: approvals.map((approval) => ({ ...approval, decidedAt: "2026-08-11T00:00:00.000Z" })) })); expect((await eligible(await signed(candidate, future), candidate)).structurallyEligible).toBe(false); });
  it.each([["presentation after confirmation", { presentation: { ...rawRequest().instance.presentation, freshUntil: "2026-08-20T00:00:00.000Z" } }], ["confirmation after plan", { confirmation: { ...rawRequest().instance.confirmation, expiresAt: "2026-08-21T00:00:00.000Z" } }], ["plan after support", { planExpiresAt: "2026-10-02T00:00:00.000Z" }], ["inverted lifecycle", undefined]] as const)("rejects expiry ordering: %s", async (name, instanceChange) => { const candidate = await request(instanceChange === undefined ? {} : { instance: { ...rawRequest().instance, ...instanceChange } }); const catalog = name === "inverted lifecycle" ? await signed(candidate, undefined, { lifecycle: { ...lifecycle, reviewBy: "2026-10-02T00:00:00.000Z" } }) : await signed(); expect((await eligible(catalog, candidate)).structurallyEligible).toBe(false); });
  it.each(["{{{subject}}}", "{{subject}}}", "{{subject}", "{subject}}", "{{sub{{ject}}", "{{subject}}{{subject}}", "{{ｓubject}}", "{{subject}}\u0000"])("rejects malformed template %s", async (template) => { const candidate = await request(); const entries = requiredDisclosureCategories.map((category) => entry(category, candidate.instance.bindingDigest, category === "operation" ? { template } : {})); expect((await eligible(await signed(candidate, entries), candidate)).structurallyEligible).toBe(false); });
  it.each([["duplicate declaration", [{ name: "subject", classification: "sensitive", redactionPolicyDigest: sha }, { name: "subject", classification: "sensitive", redactionPolicyDigest: sha }]], ["bad classification", [{ name: "subject", classification: "private", redactionPolicyDigest: sha }]], ["bad policy digest", [{ name: "subject", classification: "sensitive", redactionPolicyDigest: "bad" }]]] as const)("rejects placeholder %s", async (_name, placeholders) => { const candidate = await request(); const entries = requiredDisclosureCategories.map((category) => entry(category, candidate.instance.bindingDigest, category === "operation" ? { placeholders: placeholders as DisclosureEntry["placeholders"] } : {})); expect((await eligible(await signed(candidate, entries), candidate)).structurallyEligible).toBe(false); });
  it("rejects all runtime values and caller copy without coercion", async () => { let called = false; const attacker = { toString: () => { called = true; throw new Error("must not run"); } }; for (const values of [{ subject: "jq" }, [], "copy", 1, 1n, true, null, undefined, Symbol("x"), () => "copy", attacker]) { const candidate = await request({ values }); expect((await eligible(await signed(), candidate)).structurallyEligible).toBe(false); } const withCopy = { ...(await request()), callerCopy: attacker }; expect((await eligible(await signed(), withCopy as DisclosureRequest)).structurallyEligible).toBe(false); expect(called).toBe(false); });
  it.each([["self supersession", { supersedes: ["disclosure:operation"] }], ["self conflict", { conflictsWith: ["disclosure:operation"] }], ["duplicate supersession", { supersedes: ["disclosure:old", "disclosure:old"] }], ["conflicting references", { supersedes: ["disclosure:old"], conflictsWith: ["disclosure:old"] }]] as const)("rejects %s", async (_name, change) => { const candidate = await request(); const entries = requiredDisclosureCategories.map((category) => entry(category, candidate.instance.bindingDigest, category === "operation" ? change : {})); expect((await eligible(await signed(candidate, entries), candidate)).structurallyEligible).toBe(false); });
  it("rejects globally duplicate entry IDs", async () => { const candidate = await request(); const entries = requiredDisclosureCategories.map((category) => entry(category, candidate.instance.bindingDigest, category === "reassessment" ? { id: "disclosure:operation" } : {})); expect((await eligible(await signed(candidate, entries), candidate)).structurallyEligible).toBe(false); });
  it("returns detached immutable primitives", async () => { const candidate = await request(); const catalog = await signed(candidate); const result = await eligible(catalog, candidate); if (!result.structurallyEligible) throw new Error("expected structural terminal"); const before = JSON.stringify(result); (catalog.entries[0]!.placeholders[0] as { name: string }).name = "mutated"; expect(JSON.stringify(result)).toBe(before); expect(() => (result.entryIds as string[]).push("x")).toThrow(); });
  it("uses UTF-8 bytes for static template ceilings", async () => { const candidate = await request(); const entries = requiredDisclosureCategories.map((category) => entry(category, candidate.instance.bindingDigest, category === "operation" ? { template: "é{{subject}}", privacy: { ...entry(category, candidate.instance.bindingDigest).privacy, maxTemplateBytes: 12 } } : {})); expect((await eligible(await signed(candidate, entries), candidate)).structurallyEligible).toBe(false); });
  it("is exception-safe for exotic runtime inputs", async () => { const catalog = await signed(); class Request extends Object {} const accessor = { ...(await request()) }; Object.defineProperty(accessor, "binding", { enumerable: true, get: () => { throw new Error("no"); } }); const cycle = await request() as unknown as Record<string, unknown>; cycle.self = cycle; for (const value of [null, "x", Object.create(null), Object.assign(new Request(), await request()), accessor, cycle, { ...(await request()), [Symbol("x")]: true }]) await expect(resolveDisclosures(catalog, value as DisclosureRequest, now)).resolves.toMatchObject({ available: false, structurallyEligible: false }); await expect(disclosureBindingDigest(accessor)).resolves.toBe(""); });
  it("has no production imports, renderer, adapter, or wiring", async () => { const root = new URL("../../src/", import.meta.url); const files = (await readdir(root, { recursive: true })).filter((file) => file.endsWith(".ts") && !file.endsWith("domain/disclosure-catalog.ts") && !file.endsWith("infrastructure/disclosures/draft-disclosure-catalog.ts")); const sources = await Promise.all(files.map((file) => readFile(new URL(file, root), "utf8"))); expect(sources.join("\n")).not.toMatch(/resolveDisclosures|draftDisclosureCatalog|disclosureBindingDigest/); expect(await readFile(new URL("../../src/application/ports/package-execution.ts", import.meta.url), "utf8")).toMatch(/PackageExecutionUnavailable/); });
});
