import { readdir, readFile } from "node:fs/promises";
import { describe, expect, it } from "vitest";
import { disclosureApprovalSubjectDigest, disclosureCatalogDigest, resolveDisclosures, validateDisclosureCatalogIntegrity, type DisclosureApproval, type DisclosureCatalog, type DisclosureEntry, type DisclosureRequest } from "../../src/domain/disclosure-catalog.js";
import { draftDisclosureCatalog } from "../../src/infrastructure/disclosures/draft-disclosure-catalog.js";

const now = new Date("2026-08-10T00:00:00.000Z"); const sha = "a".repeat(64); const lifecycle = { effectiveFrom: "2026-08-01T00:00:00.000Z", reviewBy: "2026-09-01T00:00:00.000Z", supportedUntil: "2026-10-01T00:00:00.000Z" };
const target = { audience: "operator", channel: "cli", timing: "before-confirmation", severity: "warning", trigger: "package-acquisition", outcome: "planned-change" } as const;
const binding = { operation: "package-acquisition", provider: "homebrew", providerRole: "primary", capabilityId: "homebrew-formula", sideEffect: "package-install", privilege: "user", network: "required", confirmation: "required", rollback: "manual", reassessment: "required" } as const;
const instance = { requestId: "request:one", planId: "plan:one", bindingDigest: sha, confirmation: { id: "confirmation:one", requestId: "request:one", planId: "plan:one", bindingDigest: sha, decision: "accepted", expiresAt: "2026-08-11T00:00:00.000Z", consumed: false }, presentation: { id: "presentation:one", requestId: "request:one", planId: "plan:one", confirmationId: "confirmation:one", replayId: "replay:one", freshUntil: "2026-08-11T00:00:00.000Z", consumed: false } } as const;
const approvals: readonly DisclosureApproval[] = [{ role: "security", reviewer: "identity:security", decision: "approved", decidedAt: "2026-08-02T00:00:00.000Z", subjectDigest: sha, signoffRef: `sha256:${sha}` }, { role: "ux-comprehension", reviewer: "identity:ux", decision: "approved", decidedAt: "2026-08-02T00:00:00.000Z", subjectDigest: sha, signoffRef: `sha256:${sha}` }];
const baseEntry = (change: Partial<DisclosureEntry> = {}): DisclosureEntry => ({ id: "disclosure:operation", version: "1.0.0", status: "approved", owner: "identity:owner", preparer: "identity:preparer", approvals, provenance: { repository: "https://example.test/repo", commitSha: sha, artifactSha256: sha, fixture: false }, lifecycle, supersedes: [], supersededBy: "", conflictsWith: [], ambiguous: false, target: { ...target, category: "operation" }, binding, template: "Install {{package}} after confirmation.", placeholders: [{ name: "package", classification: "public" }], locale: "en-US", accessibility: "plain-text", comprehension: "reviewed", fallback: "refuse", supportRef: "support:workstation", privacy: { classification: "public", redactionPolicyDigest: sha, retention: "ephemeral", maxRenderedLength: 200 }, ...change });
async function signed(entries: readonly DisclosureEntry[] = [baseEntry()], change: Partial<DisclosureCatalog> = {}) { const bind = async (subject: unknown, candidates: readonly DisclosureApproval[]) => { const subjectDigest = await disclosureApprovalSubjectDigest(subject); return candidates.map((approval) => ({ ...approval, subjectDigest })); }; const bound = await Promise.all(entries.map(async (entry) => ({ ...entry, approvals: await bind(entry, entry.approvals) }))); const catalog: DisclosureCatalog = { schemaVersion: "DisclosureCatalogV1", id: "catalog:synthetic", version: "1.0.0", status: "approved", owner: "identity:catalog-owner", preparer: "identity:catalog-preparer", requiredApprovals: ["security", "ux-comprehension"], approvals, provenance: { repository: "https://example.test/repo", commitSha: sha, artifactSha256: sha, fixture: false }, lifecycle, requiredCategories: ["operation"], entries: bound, digest: "", ...change }; const approved = { ...catalog, approvals: await bind(catalog, catalog.approvals) }; return { ...approved, digest: await disclosureCatalogDigest(approved) }; }
const request: DisclosureRequest = { target, binding, instance, requiredCategories: ["operation"], consumedReplayIds: [], values: { package: "jq" } };
const reason = async (catalog: DisclosureCatalog, candidate: DisclosureRequest = request) => (await resolveDisclosures(catalog, candidate, now)).structurallyEligible;

describe("disclosure catalog", () => {
  it("ships an integrity-valid empty unapproved draft", async () => { expect(draftDisclosureCatalog).toMatchObject({ version: "0.1.0", status: "draft", requiredApprovals: [], entries: [] }); expect(await validateDisclosureCatalogIntegrity(draftDisclosureCatalog)).toBe(true); expect(await resolveDisclosures(draftDisclosureCatalog, request, now)).toMatchObject({ structurallyEligible: false, authority: "none", reason: "catalog-not-approved" }); });
  it("accepts a synthetic structural catalog without approving its copy or granting authority", async () => expect(resolveDisclosures(await signed(), request, now)).resolves.toMatchObject({ structurallyEligible: true, authority: "none", copyApproval: "not-established" }));
  it.each(["draft", "in-review", "rejected", "deprecated", "superseded"] as const)("rejects %s catalog status", async (status) => expect(await reason(await signed(undefined, { status }))).toBe(false));
  it.each(["draft", "in-review", "rejected", "deprecated", "superseded"] as const)("rejects %s entry status", async (status) => expect(await reason(await signed([baseEntry({ status })]))).toBe(false));
  it.each([["owner review", { approvals: [{ ...approvals[0]!, reviewer: "identity:owner" }, approvals[1]!] }], ["same reviewer", { approvals: [approvals[0]!, { ...approvals[1]!, reviewer: approvals[0]!.reviewer }] }], ["provenance fixture", { provenance: { ...baseEntry().provenance, fixture: true } }], ["future", { lifecycle: { ...lifecycle, effectiveFrom: "2026-08-11T00:00:00.000Z" } }], ["superseded", { supersededBy: "disclosure:new" }]] as const)("rejects governance %s", async (_name, change) => expect(await reason(await signed([baseEntry(change as Partial<DisclosureEntry>)]) )).toBe(false));
  it("invalidates stale approval subjects", async () => { const catalog = await signed(); const changed = { ...catalog, entries: [{ ...catalog.entries[0]!, supportRef: "support:changed" }], digest: "" }; expect(await reason({ ...changed, digest: await disclosureCatalogDigest(changed) })).toBe(false); });
  it("detects catalog tampering", async () => { const catalog = await signed(); expect(await validateDisclosureCatalogIntegrity({ ...catalog, owner: "identity:tampered" })).toBe(false); });
  it.each(Object.keys(binding))("rejects %s binding mismatch", async (key) => { const changed = { ...binding, [key]: key === "capabilityId" ? "other" : "none" } as typeof binding; expect(await reason(await signed(), { ...request, binding: changed })).toBe(false); });
  it.each([["request", { confirmation: { ...instance.confirmation, requestId: "request:other" } }], ["plan", { presentation: { ...instance.presentation, planId: "plan:other" } }], ["confirmation", { presentation: { ...instance.presentation, confirmationId: "confirmation:other" } }], ["stale", { presentation: { ...instance.presentation, freshUntil: "2026-08-09T00:00:00.000Z" } }], ["consumed confirmation", { confirmation: { ...instance.confirmation, consumed: true } }], ["consumed presentation", { presentation: { ...instance.presentation, consumed: true } }]] as const)("rejects %s instance", async (_name, change) => expect(await reason(await signed(), { ...request, instance: { ...instance, ...change } as DisclosureRequest["instance"] })).toBe(false));
  it("rejects replay and cross-binding confirmation", async () => { expect(await reason(await signed(), { ...request, consumedReplayIds: [instance.presentation.replayId] })).toBe(false); expect(await reason(await signed(), { ...request, instance: { ...instance, confirmation: { ...instance.confirmation, bindingDigest: "b".repeat(64) } } })).toBe(false); });
  it.each([["omission", []], ["duplicate", ["operation", "operation"]], ["extra", ["operation", "network"]]] as const)("rejects category %s", async (_name, requiredCategories) => expect(await reason(await signed(), { ...request, requiredCategories })).toBe(false));
  it("rejects duplicate, conflicting, and ambiguous matches", async () => { expect(await reason(await signed([baseEntry(), baseEntry({ id: "disclosure:other" })]))).toBe(false); expect(await reason(await signed([baseEntry({ conflictsWith: ["disclosure:other"] }), baseEntry({ id: "disclosure:other" })]))).toBe(false); expect(await reason(await signed([baseEntry({ ambiguous: true })]))).toBe(false); });
  it.each([["missing declaration", { placeholders: [] }], ["duplicate declaration", { placeholders: [{ name: "package", classification: "public" }, { name: "package", classification: "public" }] }], ["undeclared delimiter", { template: "Install {{other}}." }], ["duplicate delimiter", { template: "{{package}} {{package}}" }], ["sensitive placeholder", { placeholders: [{ name: "package", classification: "secret" }] }]] as const)("rejects template %s", async (_name, change) => expect(await reason(await signed([baseEntry(change as Partial<DisclosureEntry>)]))).toBe(false));
  it.each([["missing value", {}], ["extra value", { package: "jq", extra: "x" }], ["control", { package: "jq\nrm" }], ["syntax", { package: "{{secret}}" }], ["path", { package: "/home/alice/.ssh/id" }], ["credential", { package: "password=bad" }], ["environment", { package: "process.env.HOME" }], ["argv", { package: "argv[1]" }], ["log", { package: "host logs" }]] as const)("rejects runtime privacy %s", async (_name, values) => expect(await reason(await signed(), { ...request, values })).toBe(false));
  it("fails closed for exotic records, arrays, symbols, accessors, cycles, and mutation", async () => { const catalog = await signed(); const before = JSON.stringify(catalog); class Request extends Object {} class Entries extends Array<DisclosureEntry> {} const accessor = { ...request }; Object.defineProperty(accessor, "binding", { enumerable: true, get: () => binding }); const cycle = { ...request } as Record<string, unknown>; cycle.self = cycle; for (const candidate of [Object.create(request), Object.assign(new Request(), request), Object.assign(Object.create(null), request), accessor, { ...request, [Symbol("x")]: true }, cycle, { ...request, extra: true }]) expect(await reason(catalog, candidate as DisclosureRequest)).toBe(false); expect(await reason({ ...catalog, entries: Entries.from(catalog.entries) })).toBe(false); expect(JSON.stringify(catalog)).toBe(before); });
  it("has no imports, wiring, adapters, or production availability", async () => { const root = new URL("../../src/", import.meta.url); const files = (await readdir(root, { recursive: true })).filter((file) => file.endsWith(".ts") && !file.endsWith("domain/disclosure-catalog.ts") && !file.endsWith("infrastructure/disclosures/draft-disclosure-catalog.ts")); const sources = await Promise.all(files.map((file) => readFile(new URL(file, root), "utf8"))); expect(sources.join("\n")).not.toMatch(/resolveDisclosures|draftDisclosureCatalog/); expect(await readFile(new URL("../../src/application/ports/package-execution.ts", import.meta.url), "utf8")).toMatch(/PackageExecutionUnavailable/); });
});
