export type DisclosureStatus = "draft" | "in-review" | "approved" | "rejected" | "deprecated" | "superseded";
export type DisclosureRole = "security" | "ux-comprehension";
export type DisclosureCategory = "operation" | "side-effects" | "privilege" | "network" | "confirmation" | "rollback" | "reassessment";
export interface DisclosureApproval { readonly role: DisclosureRole; readonly reviewer: string; readonly decision: "approved" | "rejected"; readonly decidedAt: string; readonly subjectDigest: string; readonly signoffRef: string }
export interface DisclosureProvenance { readonly repository: string; readonly commitSha: string; readonly artifactSha256: string; readonly fixture: boolean }
export interface DisclosureWindow { readonly effectiveFrom: string; readonly reviewBy: string; readonly supportedUntil: string }
export interface DisclosureTarget { readonly audience: "operator" | "administrator"; readonly channel: "cli" | "tui"; readonly timing: "before-confirmation"; readonly severity: "info" | "warning" | "critical"; readonly category: DisclosureCategory; readonly trigger: "package-acquisition" | "configuration-apply"; readonly outcome: "planned-change" | "refusal" | "reassessment-required" }
export interface DisclosureBinding { readonly operation: "package-acquisition" | "configuration-apply"; readonly provider: "omarchy" | "homebrew"; readonly providerRole: "primary" | "fallback"; readonly capabilityId: string; readonly sideEffect: "package-install" | "configuration-write"; readonly privilege: "user" | "elevated"; readonly network: "required" | "none"; readonly confirmation: "required"; readonly rollback: "manual" | "none"; readonly reassessment: "required" | "none" }
export interface DisclosureInstance { readonly requestId: string; readonly planId: string; readonly planExpiresAt: string; readonly bindingDigest: string; readonly confirmation: { readonly id: string; readonly requestId: string; readonly planId: string; readonly bindingDigest: string; readonly decision: "accepted"; readonly expiresAt: string; readonly consumed: boolean }; readonly presentation: { readonly id: string; readonly requestId: string; readonly planId: string; readonly confirmationId: string; readonly replayId: string; readonly freshUntil: string; readonly consumed: boolean } }
export interface DisclosureEntry { readonly id: string; readonly version: string; readonly status: DisclosureStatus; readonly owner: string; readonly preparer: string; readonly approvals: readonly DisclosureApproval[]; readonly provenance: DisclosureProvenance; readonly lifecycle: DisclosureWindow; readonly supersedes: readonly string[]; readonly supersededBy: string; readonly conflictsWith: readonly string[]; readonly ambiguous: boolean; readonly target: DisclosureTarget; readonly binding: DisclosureBinding; readonly bindingDigest: string; readonly template: string; readonly placeholders: readonly { readonly name: string; readonly classification: "public" | "sensitive" | "secret"; readonly redactionPolicyDigest: string }[]; readonly locale: "en-US"; readonly accessibility: "plain-text"; readonly comprehension: "external-review-required"; readonly fallback: "refuse"; readonly supportRef: string; readonly privacy: { readonly classification: "public" | "internal"; readonly redactionPolicyDigest: string; readonly retention: "ephemeral" | "bounded"; readonly maxTemplateBytes: number } }
export interface DisclosureCatalog { readonly schemaVersion: "DisclosureCatalogV1"; readonly id: string; readonly version: string; readonly status: DisclosureStatus; readonly owner: string; readonly preparer: string; readonly requiredApprovals: readonly DisclosureRole[]; readonly approvals: readonly DisclosureApproval[]; readonly provenance?: DisclosureProvenance; readonly lifecycle: DisclosureWindow; readonly requiredCategories: readonly DisclosureCategory[]; readonly entries: readonly DisclosureEntry[]; readonly digest: string }
export interface DisclosureRequest { readonly target: Omit<DisclosureTarget, "category">; readonly binding: DisclosureBinding; readonly instance: DisclosureInstance; readonly requiredCategories: readonly DisclosureCategory[]; readonly consumedReplayIds: readonly string[]; readonly values: unknown }
export type DisclosureResolution = { readonly available: false; readonly structurallyEligible: true; readonly reason: "independent-copy-review-required"; readonly authority: "none"; readonly copyApproval: "not-established"; readonly catalogId: string; readonly catalogDigest: string; readonly bindingDigest: string; readonly entryIds: readonly string[]; readonly entrySubjectDigests: readonly string[] } | { readonly available: false; readonly structurallyEligible: false; readonly authority: "none"; readonly reason: "integrity-invalid" | "catalog-not-approved" | "policy-invalid" | "approval-invalid" | "outside-window" | "binding-mismatch" | "instance-invalid" | "entry-not-approved" | "ambiguous" | "template-invalid" | "runtime-values-unsupported" };

export const requiredDisclosureCategories = Object.freeze(["operation", "side-effects", "privilege", "network", "confirmation", "rollback", "reassessment"] as const);
const statuses = ["draft", "in-review", "approved", "rejected", "deprecated", "superseded"] as const; const roles = ["security", "ux-comprehension"] as const;
const sha = /^[a-f0-9]{64}$/; const signoff = /^sha256:[a-f0-9]{64}$/; const identifier = /^[a-z][a-z0-9-]*:[a-z0-9._+-]+$/; const semver = /^\d+\.\d+\.\d+$/; const canonicalName = /^[a-z][a-z0-9_]*$/;
const text = (value: unknown): value is string => typeof value === "string" && value.length > 0 && value === value.trim() && !/[\u0000-\u001f\u007f]/.test(value);
const closed = <T extends string>(values: readonly T[], value: unknown): value is T => typeof value === "string" && values.includes(value as T);
const time = (value: unknown): value is string => text(value) && Number.isFinite(Date.parse(value)) && new Date(value).toISOString() === value;
const exact = (value: unknown, keys: readonly string[]): value is Record<string, unknown> => data(value) && Object.keys(value).length === keys.length && keys.every((key) => Object.hasOwn(value, key));
const array = <T>(value: readonly T[], valid: (item: T) => boolean) => dense(value) && value.every(valid); const unique = <T>(value: readonly T[]) => new Set(value).size === value.length;
const same = (left: object, right: object) => Object.keys(left).length === Object.keys(right).length && Object.keys(left).every((key) => (left as Record<string, unknown>)[key] === (right as Record<string, unknown>)[key]);
const exactCategories = (value: readonly DisclosureCategory[]) => array(value, (item) => closed(requiredDisclosureCategories, item)) && value.length === requiredDisclosureCategories.length && unique(value) && requiredDisclosureCategories.every((item, index) => value[index] === item);
const validWindow = (value: DisclosureWindow) => exact(value, ["effectiveFrom", "reviewBy", "supportedUntil"]) && time(value.effectiveFrom) && time(value.reviewBy) && time(value.supportedUntil) && Date.parse(value.effectiveFrom) <= Date.parse(value.reviewBy) && Date.parse(value.reviewBy) <= Date.parse(value.supportedUntil);
const current = (value: DisclosureWindow, now: Date) => validWindow(value) && Date.parse(value.effectiveFrom) <= now.getTime() && now.getTime() <= Date.parse(value.reviewBy) && now.getTime() <= Date.parse(value.supportedUntil);
const validProvenance = (value: DisclosureProvenance) => exact(value, ["repository", "commitSha", "artifactSha256", "fixture"]) && text(value.repository) && sha.test(value.commitSha) && sha.test(value.artifactSha256) && value.fixture === false;
const targetKeys = ["audience", "channel", "timing", "severity", "category", "trigger", "outcome"] as const;
const validTarget = (value: DisclosureTarget) => exact(value, targetKeys) && closed(["operator", "administrator"] as const, value.audience) && closed(["cli", "tui"] as const, value.channel) && value.timing === "before-confirmation" && closed(["info", "warning", "critical"] as const, value.severity) && closed(requiredDisclosureCategories, value.category) && closed(["package-acquisition", "configuration-apply"] as const, value.trigger) && closed(["planned-change", "refusal", "reassessment-required"] as const, value.outcome);
const bindingKeys = ["operation", "provider", "providerRole", "capabilityId", "sideEffect", "privilege", "network", "confirmation", "rollback", "reassessment"] as const;
const validBinding = (value: DisclosureBinding) => exact(value, bindingKeys) && closed(["package-acquisition", "configuration-apply"] as const, value.operation) && closed(["omarchy", "homebrew"] as const, value.provider) && closed(["primary", "fallback"] as const, value.providerRole) && text(value.capabilityId) && closed(["package-install", "configuration-write"] as const, value.sideEffect) && closed(["user", "elevated"] as const, value.privilege) && closed(["required", "none"] as const, value.network) && value.confirmation === "required" && closed(["manual", "none"] as const, value.rollback) && closed(["required", "none"] as const, value.reassessment);
const validRelationship = (target: DisclosureTarget, binding: DisclosureBinding) => target.trigger === binding.operation && ((binding.operation === "package-acquisition" && binding.sideEffect === "package-install") || (binding.operation === "configuration-apply" && binding.sideEffect === "configuration-write")) && (target.outcome !== "reassessment-required" || binding.reassessment === "required");
const validApprovals = async (owner: string, preparer: string, approvals: readonly DisclosureApproval[], subject: unknown, now: Date) => { const digest = await disclosureApprovalSubjectDigest(subject); return array(approvals, (approval) => exact(approval, ["role", "reviewer", "decision", "decidedAt", "subjectDigest", "signoffRef"]) && closed(roles, approval.role) && identifier.test(approval.reviewer) && approval.decision === "approved" && time(approval.decidedAt) && Date.parse(approval.decidedAt) <= now.getTime() && approval.subjectDigest === digest && signoff.test(approval.signoffRef)) && approvals.length === roles.length && roles.every((role) => approvals.some((approval) => approval.role === role)) && unique(approvals.map((approval) => approval.reviewer)) && approvals.every((approval) => approval.reviewer !== owner && approval.reviewer !== preparer); };
const scanTemplate = (value: unknown) => { if (!text(value) || value.normalize("NFC") !== value || /[\p{Cc}\p{Cf}\ufe5b\ufe5c\uff01-\uff5e]/u.test(value)) return undefined; const tokens: string[] = []; for (let index = 0; index < value.length;) { if (value[index] === "}") return undefined; if (value[index] !== "{") { index++; continue; } if (value[index + 1] !== "{") return undefined; const end = value.indexOf("}}", index + 2); if (end < 0) return undefined; const name = value.slice(index + 2, end); if (!canonicalName.test(name)) return undefined; tokens.push(name); index = end + 2; } return tokens; };
const validTemplate = (entry: DisclosureEntry) => { const tokens = scanTemplate(entry.template); if (tokens === undefined || !array(entry.placeholders, (item) => exact(item, ["name", "classification", "redactionPolicyDigest"]) && canonicalName.test(item.name) && closed(["public", "sensitive", "secret"] as const, item.classification) && sha.test(item.redactionPolicyDigest) && item.redactionPolicyDigest === entry.privacy.redactionPolicyDigest)) return false; const names = entry.placeholders.map((item) => item.name); return unique(tokens) && unique(names) && tokens.length === names.length && names.every((name) => tokens.includes(name)) && new TextEncoder().encode(entry.template).length <= entry.privacy.maxTemplateBytes; };
const entryKeys = ["id", "version", "status", "owner", "preparer", "approvals", "provenance", "lifecycle", "supersedes", "supersededBy", "conflictsWith", "ambiguous", "target", "binding", "bindingDigest", "template", "placeholders", "locale", "accessibility", "comprehension", "fallback", "supportRef", "privacy"] as const;
const validEntry = (entry: DisclosureEntry, now: Date) => exact(entry, entryKeys) && identifier.test(entry.id) && semver.test(entry.version) && closed(statuses, entry.status) && identifier.test(entry.owner) && (entry.preparer === "" || identifier.test(entry.preparer)) && entry.owner !== entry.preparer && validProvenance(entry.provenance) && current(entry.lifecycle, now) && array(entry.supersedes, identifier.test.bind(identifier)) && unique(entry.supersedes) && !entry.supersedes.includes(entry.id) && (entry.supersededBy === "" || identifier.test(entry.supersededBy)) && entry.supersededBy !== entry.id && array(entry.conflictsWith, identifier.test.bind(identifier)) && unique(entry.conflictsWith) && !entry.conflictsWith.includes(entry.id) && !entry.conflictsWith.some((value) => entry.supersedes.includes(value) || value === entry.supersededBy) && typeof entry.ambiguous === "boolean" && validTarget(entry.target) && validBinding(entry.binding) && validRelationship(entry.target, entry.binding) && sha.test(entry.bindingDigest) && entry.locale === "en-US" && entry.accessibility === "plain-text" && entry.comprehension === "external-review-required" && entry.fallback === "refuse" && identifier.test(entry.supportRef) && exact(entry.privacy, ["classification", "redactionPolicyDigest", "retention", "maxTemplateBytes"]) && closed(["public", "internal"] as const, entry.privacy.classification) && sha.test(entry.privacy.redactionPolicyDigest) && closed(["ephemeral", "bounded"] as const, entry.privacy.retention) && Number.isSafeInteger(entry.privacy.maxTemplateBytes) && entry.privacy.maxTemplateBytes > 0 && validTemplate(entry);
const instanceShape = (value: unknown) => exact(value, ["requestId", "planId", "planExpiresAt", "bindingDigest", "confirmation", "presentation"]) && exact(value.confirmation, ["id", "requestId", "planId", "bindingDigest", "decision", "expiresAt", "consumed"]) && exact(value.presentation, ["id", "requestId", "planId", "confirmationId", "replayId", "freshUntil", "consumed"]);

export async function disclosureCatalogDigest(catalog: DisclosureCatalog): Promise<string> { try { const { digest: _digest, ...subject } = catalog; return hash(canonical(subject)); } catch { return ""; } }
export async function disclosureApprovalSubjectDigest(subject: unknown): Promise<string> { try { return hash(canonical(stripApprovals(subject))); } catch { return ""; } }
export async function disclosureBindingDigest(request: unknown): Promise<string> { try { if (!exact(request, ["target", "binding", "instance", "requiredCategories", "consumedReplayIds", "values"]) || !instanceShape(request.instance)) return ""; const instance = request.instance as unknown as DisclosureInstance; return hash(canonical({ target: request.target, binding: request.binding, requiredCategories: request.requiredCategories, consumedReplayIds: request.consumedReplayIds, instance: { requestId: instance.requestId, planId: instance.planId, planExpiresAt: instance.planExpiresAt, confirmation: { id: instance.confirmation.id, requestId: instance.confirmation.requestId, planId: instance.confirmation.planId, decision: instance.confirmation.decision, expiresAt: instance.confirmation.expiresAt, consumed: instance.confirmation.consumed }, presentation: instance.presentation } })); } catch { return ""; } }
export async function validateDisclosureCatalogIntegrity(catalog: DisclosureCatalog): Promise<boolean> { try { return data(catalog) && sha.test(catalog.digest) && catalog.digest === await disclosureCatalogDigest(catalog); } catch { return false; } }
export async function resolveDisclosures(catalog: DisclosureCatalog, request: DisclosureRequest, now: Date): Promise<DisclosureResolution> { try {
  if (!await validateDisclosureCatalogIntegrity(catalog)) return no("integrity-invalid"); if (catalog.status !== "approved") return no("catalog-not-approved"); if (!(now instanceof Date) || Object.getPrototypeOf(now) !== Date.prototype || !Number.isFinite(now.getTime())) return no("policy-invalid");
  if (!exact(catalog, ["schemaVersion", "id", "version", "status", "owner", "preparer", "requiredApprovals", "approvals", "provenance", "lifecycle", "requiredCategories", "entries", "digest"]) || catalog.schemaVersion !== "DisclosureCatalogV1" || !identifier.test(catalog.id) || !semver.test(catalog.version) || !identifier.test(catalog.owner) || (catalog.preparer !== "" && !identifier.test(catalog.preparer)) || catalog.owner === catalog.preparer || !array(catalog.requiredApprovals, (role) => closed(roles, role)) || !unique(catalog.requiredApprovals) || !roles.every((role) => catalog.requiredApprovals.includes(role)) || catalog.provenance === undefined || !validProvenance(catalog.provenance) || !current(catalog.lifecycle, now) || !exactCategories(catalog.requiredCategories) || !array(catalog.entries, data) || catalog.entries.length !== requiredDisclosureCategories.length) return no("policy-invalid");
  if (!await validApprovals(catalog.owner, catalog.preparer, catalog.approvals, catalog, now)) return no("approval-invalid");
  if (!exact(request, ["target", "binding", "instance", "requiredCategories", "consumedReplayIds", "values"]) || !exact(request.target, ["audience", "channel", "timing", "severity", "trigger", "outcome"]) || !validTarget({ ...request.target, category: requiredDisclosureCategories[0] }) || !validBinding(request.binding) || !validRelationship({ ...request.target, category: requiredDisclosureCategories[0] }, request.binding) || !exactCategories(request.requiredCategories) || !array(request.consumedReplayIds, identifier.test.bind(identifier)) || !unique(request.consumedReplayIds)) return no("binding-mismatch");
  if (!data(request.values) || Object.keys(request.values).length !== 0) return no("runtime-values-unsupported"); if (!instanceShape(request.instance)) return no("instance-invalid");
  const instance = request.instance; const ids = [instance.requestId, instance.planId, instance.confirmation.id, instance.presentation.id, instance.presentation.replayId]; const expectedDigest = await disclosureBindingDigest(request);
  if (!ids.every(identifier.test.bind(identifier)) || !unique(ids) || !sha.test(expectedDigest) || instance.bindingDigest !== expectedDigest || instance.confirmation.bindingDigest !== expectedDigest || instance.confirmation.requestId !== instance.requestId || instance.confirmation.planId !== instance.planId || instance.confirmation.decision !== "accepted" || instance.confirmation.consumed !== false || instance.presentation.requestId !== instance.requestId || instance.presentation.planId !== instance.planId || instance.presentation.confirmationId !== instance.confirmation.id || instance.presentation.consumed !== false || request.consumedReplayIds.includes(instance.presentation.replayId) || ![instance.planExpiresAt, instance.confirmation.expiresAt, instance.presentation.freshUntil].every(time) || now.getTime() > Date.parse(instance.presentation.freshUntil) || Date.parse(instance.presentation.freshUntil) > Date.parse(instance.confirmation.expiresAt) || Date.parse(instance.confirmation.expiresAt) > Date.parse(instance.planExpiresAt) || Date.parse(instance.planExpiresAt) > Date.parse(catalog.lifecycle.reviewBy) || Date.parse(instance.planExpiresAt) > Date.parse(catalog.lifecycle.supportedUntil)) return no("instance-invalid");
  if (!unique([catalog.id, ...catalog.entries.map((entry) => entry.id)])) return no("policy-invalid"); const selected = requiredDisclosureCategories.map((category) => catalog.entries.filter((entry) => data(entry.target) && data(entry.binding) && entry.target.category === category && same({ ...entry.target, category: undefined }, { ...request.target, category: undefined }) && same(entry.binding, request.binding)));
  if (selected.some((entries) => entries.length !== 1) || selected.flat().length !== catalog.entries.length) return no(selected.some((entries) => entries.length > 1) ? "ambiguous" : "binding-mismatch"); const entries = selected.map((items) => items[0]!);
  for (const entry of entries) { if (!validEntry(entry, now) || entry.status !== "approved" || entry.supersededBy !== "" || entry.bindingDigest !== expectedDigest) return no("entry-not-approved"); if (entry.ambiguous || entry.conflictsWith.length > 0) return no("ambiguous"); if (!await validApprovals(entry.owner, entry.preparer, entry.approvals, entry, now)) return no("approval-invalid"); if (Date.parse(instance.planExpiresAt) > Date.parse(entry.lifecycle.reviewBy) || Date.parse(instance.planExpiresAt) > Date.parse(entry.lifecycle.supportedUntil)) return no("instance-invalid"); }
  const entryIds = Object.freeze(entries.map((entry) => entry.id)); const entrySubjectDigests = Object.freeze(await Promise.all(entries.map(disclosureApprovalSubjectDigest))); return Object.freeze({ available: false, structurallyEligible: true, reason: "independent-copy-review-required", authority: "none", copyApproval: "not-established", catalogId: catalog.id, catalogDigest: catalog.digest, bindingDigest: expectedDigest, entryIds, entrySubjectDigests });
} catch { return no("policy-invalid"); } }
const no = (reason: Exclude<DisclosureResolution, { structurallyEligible: true }>["reason"]): DisclosureResolution => Object.freeze({ available: false, structurallyEligible: false, authority: "none", reason });
const data = (value: unknown): value is Record<string, unknown> => { if (typeof value !== "object" || value === null || Array.isArray(value) || Object.getPrototypeOf(value) !== Object.prototype) return false; const keys = Object.keys(value); const descriptors = Object.getOwnPropertyDescriptors(value); return Reflect.ownKeys(value).length === keys.length && !keys.some((key) => ["__proto__", "prototype", "constructor"].includes(key)) && keys.every((key) => descriptors[key]?.enumerable && "value" in descriptors[key]!); };
const dense = (value: unknown) => { if (!Array.isArray(value) || Object.getPrototypeOf(value) !== Array.prototype) return false; const keys = Reflect.ownKeys(value).filter((key) => key !== "length"); const descriptors = Object.getOwnPropertyDescriptors(value); return keys.length === value.length && keys.every((key, index) => key === String(index) && descriptors[String(index)]?.enumerable && "value" in descriptors[String(index)]!); };
function canonical(value: unknown, seen = new Set<object>()): string { if (value === null || typeof value === "string" || typeof value === "boolean" || (typeof value === "number" && Number.isFinite(value))) return JSON.stringify(value); if (typeof value !== "object" || seen.has(value)) throw new TypeError("non-canonical"); seen.add(value); try { if (Array.isArray(value)) { if (!dense(value)) throw new TypeError("non-canonical"); return `[${value.map((item) => canonical(item, seen)).join(",")}]`; } if (!data(value)) throw new TypeError("non-canonical"); return `{${Object.keys(value).sort().map((key) => `${JSON.stringify(key)}:${canonical(value[key], seen)}`).join(",")}}`; } finally { seen.delete(value); } }
function stripApprovals(value: unknown): unknown { if (Array.isArray(value)) { if (!dense(value)) throw new TypeError("non-canonical"); return value.map(stripApprovals); } if (value !== null && typeof value === "object") { if (!data(value)) throw new TypeError("non-canonical"); return Object.fromEntries(Object.keys(value).filter((key) => !["approvals", "subjectDigest", "signoffRef", "digest"].includes(key)).map((key) => [key, stripApprovals(value[key])])); } return value; }
async function hash(value: string) { const digest = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(value)); return [...new Uint8Array(digest)].map((byte) => byte.toString(16).padStart(2, "0")).join(""); }
