export type DisclosureStatus = "draft" | "in-review" | "approved" | "rejected" | "deprecated" | "superseded";
export type DisclosureRole = "security" | "ux-comprehension";
export type DisclosureCategory = "operation" | "side-effects" | "privilege" | "network" | "confirmation" | "rollback" | "reassessment";
export interface DisclosureApproval { readonly role: DisclosureRole; readonly reviewer: string; readonly decision: "approved" | "rejected"; readonly decidedAt: string; readonly subjectDigest: string; readonly signoffRef: string }
export interface DisclosureProvenance { readonly repository: string; readonly commitSha: string; readonly artifactSha256: string; readonly fixture: boolean }
export interface DisclosureWindow { readonly effectiveFrom: string; readonly reviewBy: string; readonly supportedUntil: string }
export interface DisclosureTarget { readonly audience: "operator" | "administrator"; readonly channel: "cli" | "tui"; readonly timing: "before-confirmation"; readonly severity: "info" | "warning" | "critical"; readonly category: DisclosureCategory; readonly trigger: "package-acquisition" | "configuration-apply"; readonly outcome: "planned-change" | "refusal" | "reassessment-required" }
export interface DisclosureBinding { readonly operation: "package-acquisition" | "configuration-apply"; readonly provider: "omarchy" | "homebrew"; readonly providerRole: "primary" | "fallback"; readonly capabilityId: string; readonly sideEffect: "package-install" | "configuration-write"; readonly privilege: "user" | "elevated"; readonly network: "required" | "none"; readonly confirmation: "required"; readonly rollback: "manual" | "none"; readonly reassessment: "required" | "none" }
export interface DisclosureInstance { readonly requestId: string; readonly planId: string; readonly bindingDigest: string; readonly confirmation: { readonly id: string; readonly requestId: string; readonly planId: string; readonly bindingDigest: string; readonly decision: "accepted"; readonly expiresAt: string; readonly consumed: boolean }; readonly presentation: { readonly id: string; readonly requestId: string; readonly planId: string; readonly confirmationId: string; readonly replayId: string; readonly freshUntil: string; readonly consumed: boolean } }
export interface DisclosureEntry { readonly id: string; readonly version: string; readonly status: DisclosureStatus; readonly owner: string; readonly preparer: string; readonly approvals: readonly DisclosureApproval[]; readonly provenance: DisclosureProvenance; readonly lifecycle: DisclosureWindow; readonly supersedes: readonly string[]; readonly supersededBy: string; readonly conflictsWith: readonly string[]; readonly ambiguous: boolean; readonly target: DisclosureTarget; readonly binding: DisclosureBinding; readonly template: string; readonly placeholders: readonly { readonly name: string; readonly classification: "public" | "sensitive" | "secret" }[]; readonly locale: "en-US"; readonly accessibility: "plain-text"; readonly comprehension: "reviewed"; readonly fallback: "refuse"; readonly supportRef: string; readonly privacy: { readonly classification: "public" | "internal"; readonly redactionPolicyDigest: string; readonly retention: "ephemeral" | "bounded"; readonly maxRenderedLength: number } }
export interface DisclosureCatalog { readonly schemaVersion: "DisclosureCatalogV1"; readonly id: string; readonly version: string; readonly status: DisclosureStatus; readonly owner: string; readonly preparer: string; readonly requiredApprovals: readonly DisclosureRole[]; readonly approvals: readonly DisclosureApproval[]; readonly provenance?: DisclosureProvenance; readonly lifecycle: DisclosureWindow; readonly requiredCategories: readonly DisclosureCategory[]; readonly entries: readonly DisclosureEntry[]; readonly digest: string }
export interface DisclosureRequest { readonly target: Omit<DisclosureTarget, "category">; readonly binding: DisclosureBinding; readonly instance: DisclosureInstance; readonly requiredCategories: readonly DisclosureCategory[]; readonly consumedReplayIds: readonly string[]; readonly values: Record<string, string> }
export type DisclosureResolution = { readonly structurallyEligible: true; readonly authority: "none"; readonly copyApproval: "not-established"; readonly entries: readonly DisclosureEntry[] } | { readonly structurallyEligible: false; readonly authority: "none"; readonly reason: "integrity-invalid" | "catalog-not-approved" | "policy-invalid" | "approval-invalid" | "outside-window" | "binding-mismatch" | "instance-invalid" | "entry-not-approved" | "ambiguous" | "template-invalid" | "privacy-invalid" };

const statuses = ["draft", "in-review", "approved", "rejected", "deprecated", "superseded"] as const;
const roles = ["security", "ux-comprehension"] as const;
const categories = ["operation", "side-effects", "privilege", "network", "confirmation", "rollback", "reassessment"] as const;
const sha = /^[a-f0-9]{64}$/; const signoff = /^sha256:[a-f0-9]{64}$/; const id = /^[a-z][a-z0-9-]*:[a-z0-9._+-]+$/; const semver = /^\d+\.\d+\.\d+$/;
const sensitive = /[\u0000-\u001f\u007f]|\{\{|\}\}|secret|token|password|credential|private[_ -]?key|(?:^|\s)(?:\/home\/|\/Users\/)|process\.env|(?:^|\W)(?:argv|logs?|username|hostname|user|host)(?:\W|$)/i;
const text = (value: unknown): value is string => typeof value === "string" && value.length > 0 && value === value.trim();
const safe = (value: unknown): value is string => text(value) && !sensitive.test(value);
const closed = <T extends string>(values: readonly T[], value: unknown): value is T => typeof value === "string" && values.includes(value as T);
const time = (value: unknown): value is string => text(value) && Number.isFinite(Date.parse(value)) && new Date(value).toISOString() === value;
const exact = (value: unknown, keys: readonly string[]): value is Record<string, unknown> => data(value) && Object.keys(value).length === keys.length && keys.every((key) => Object.hasOwn(value, key));
const array = <T>(value: readonly T[], valid: (item: T) => boolean) => dense(value) && value.every(valid);
const unique = <T>(value: readonly T[]) => new Set(value).size === value.length;
const same = (left: object, right: object) => Object.keys(left).length === Object.keys(right).length && Object.keys(left).every((key) => (left as Record<string, unknown>)[key] === (right as Record<string, unknown>)[key]);
const validWindow = (value: DisclosureWindow) => exact(value, ["effectiveFrom", "reviewBy", "supportedUntil"]) && time(value.effectiveFrom) && time(value.reviewBy) && time(value.supportedUntil) && Date.parse(value.effectiveFrom) <= Date.parse(value.reviewBy) && Date.parse(value.reviewBy) <= Date.parse(value.supportedUntil);
const current = (value: DisclosureWindow, now: Date) => validWindow(value) && Date.parse(value.effectiveFrom) <= now.getTime() && now.getTime() <= Date.parse(value.reviewBy) && now.getTime() <= Date.parse(value.supportedUntil);
const validProvenance = (value: DisclosureProvenance) => exact(value, ["repository", "commitSha", "artifactSha256", "fixture"]) && safe(value.repository) && sha.test(value.commitSha) && sha.test(value.artifactSha256) && value.fixture === false;
const validTarget = (value: DisclosureTarget) => exact(value, ["audience", "channel", "timing", "severity", "category", "trigger", "outcome"]) && closed(["operator", "administrator"] as const, value.audience) && closed(["cli", "tui"] as const, value.channel) && value.timing === "before-confirmation" && closed(["info", "warning", "critical"] as const, value.severity) && closed(categories, value.category) && closed(["package-acquisition", "configuration-apply"] as const, value.trigger) && closed(["planned-change", "refusal", "reassessment-required"] as const, value.outcome);
const bindingKeys = ["operation", "provider", "providerRole", "capabilityId", "sideEffect", "privilege", "network", "confirmation", "rollback", "reassessment"] as const;
const validBinding = (value: DisclosureBinding) => exact(value, bindingKeys) && closed(["package-acquisition", "configuration-apply"] as const, value.operation) && closed(["omarchy", "homebrew"] as const, value.provider) && closed(["primary", "fallback"] as const, value.providerRole) && safe(value.capabilityId) && closed(["package-install", "configuration-write"] as const, value.sideEffect) && closed(["user", "elevated"] as const, value.privilege) && closed(["required", "none"] as const, value.network) && value.confirmation === "required" && closed(["manual", "none"] as const, value.rollback) && closed(["required", "none"] as const, value.reassessment);
const validApprovals = async (owner: string, preparer: string, approvals: readonly DisclosureApproval[], subject: unknown) => { const subjectDigest = await disclosureApprovalSubjectDigest(subject); return array(approvals, (approval) => exact(approval, ["role", "reviewer", "decision", "decidedAt", "subjectDigest", "signoffRef"]) && closed(roles, approval.role) && id.test(approval.reviewer) && approval.decision === "approved" && time(approval.decidedAt) && signoff.test(approval.signoffRef) && approval.subjectDigest === subjectDigest) && approvals.length === roles.length && roles.every((role) => approvals.some((approval) => approval.role === role)) && unique(approvals.map((approval) => approval.reviewer)) && approvals.every((approval) => approval.reviewer !== owner && approval.reviewer !== preparer); };
const validInstance = (value: DisclosureInstance, consumed: readonly string[], now: Date) => exact(value, ["requestId", "planId", "bindingDigest", "confirmation", "presentation"]) && [value.requestId, value.planId].every(id.test.bind(id)) && sha.test(value.bindingDigest)
  && exact(value.confirmation, ["id", "requestId", "planId", "bindingDigest", "decision", "expiresAt", "consumed"]) && id.test(value.confirmation.id) && value.confirmation.requestId === value.requestId && value.confirmation.planId === value.planId && value.confirmation.bindingDigest === value.bindingDigest && value.confirmation.decision === "accepted" && time(value.confirmation.expiresAt) && now.getTime() <= Date.parse(value.confirmation.expiresAt) && value.confirmation.consumed === false
  && exact(value.presentation, ["id", "requestId", "planId", "confirmationId", "replayId", "freshUntil", "consumed"]) && [value.presentation.id, value.presentation.replayId].every(id.test.bind(id)) && value.presentation.requestId === value.requestId && value.presentation.planId === value.planId && value.presentation.confirmationId === value.confirmation.id && time(value.presentation.freshUntil) && now.getTime() <= Date.parse(value.presentation.freshUntil) && value.presentation.consumed === false && !consumed.includes(value.presentation.replayId) && unique([value.requestId, value.planId, value.confirmation.id, value.presentation.id, value.presentation.replayId]);
const validTemplate = (entry: DisclosureEntry, values: Record<string, string>) => { if (!safe(entry.template.replace(/\{\{[a-z][a-z0-9_]*\}\}/g, "placeholder")) || !array(entry.placeholders, (item) => exact(item, ["name", "classification"]) && /^[a-z][a-z0-9_]*$/.test(item.name) && closed(["public", "sensitive", "secret"] as const, item.classification)) || !unique(entry.placeholders.map((item) => item.name)) || entry.placeholders.some((item) => item.classification !== "public") || !data(values)) return false;
  const tokens = [...entry.template.matchAll(/\{\{([a-z][a-z0-9_]*)\}\}/g)].map((match) => match[1]!); const names = entry.placeholders.map((item) => item.name); return unique(tokens) && tokens.length === names.length && names.every((name) => tokens.includes(name)) && Object.keys(values).length === names.length && names.every((name) => Object.hasOwn(values, name) && safe(values[name])) && entry.template.replace(/\{\{([a-z][a-z0-9_]*)\}\}/g, (_token, name: string) => values[name]!).length <= entry.privacy.maxRenderedLength; };
const validEntry = (entry: DisclosureEntry, now: Date) => exact(entry, ["id", "version", "status", "owner", "preparer", "approvals", "provenance", "lifecycle", "supersedes", "supersededBy", "conflictsWith", "ambiguous", "target", "binding", "template", "placeholders", "locale", "accessibility", "comprehension", "fallback", "supportRef", "privacy"]) && id.test(entry.id) && semver.test(entry.version) && closed(statuses, entry.status) && id.test(entry.owner) && (entry.preparer === "" || id.test(entry.preparer)) && entry.owner !== entry.preparer && validProvenance(entry.provenance) && current(entry.lifecycle, now) && array(entry.supersedes, id.test.bind(id)) && (entry.supersededBy === "" || id.test(entry.supersededBy)) && array(entry.conflictsWith, id.test.bind(id)) && typeof entry.ambiguous === "boolean" && validTarget(entry.target) && validBinding(entry.binding) && entry.locale === "en-US" && entry.accessibility === "plain-text" && entry.comprehension === "reviewed" && entry.fallback === "refuse" && id.test(entry.supportRef) && exact(entry.privacy, ["classification", "redactionPolicyDigest", "retention", "maxRenderedLength"]) && closed(["public", "internal"] as const, entry.privacy.classification) && sha.test(entry.privacy.redactionPolicyDigest) && closed(["ephemeral", "bounded"] as const, entry.privacy.retention) && Number.isSafeInteger(entry.privacy.maxRenderedLength) && entry.privacy.maxRenderedLength > 0 && entry.template.length <= entry.privacy.maxRenderedLength;

export async function disclosureCatalogDigest(catalog: DisclosureCatalog): Promise<string> { try { const { digest: _digest, ...subject } = catalog; return hash(canonical(subject)); } catch { return ""; } }
export async function disclosureApprovalSubjectDigest(subject: unknown): Promise<string> { try { return hash(canonical(stripApprovals(subject))); } catch { return ""; } }
export async function validateDisclosureCatalogIntegrity(catalog: DisclosureCatalog): Promise<boolean> { try { return data(catalog) && sha.test(catalog.digest) && catalog.digest === await disclosureCatalogDigest(catalog); } catch { return false; } }
export async function resolveDisclosures(catalog: DisclosureCatalog, request: DisclosureRequest, now: Date): Promise<DisclosureResolution> { try {
  if (!await validateDisclosureCatalogIntegrity(catalog)) return no("integrity-invalid"); if (catalog.status !== "approved") return no("catalog-not-approved");
  if (!exact(catalog, ["schemaVersion", "id", "version", "status", "owner", "preparer", "requiredApprovals", "approvals", "provenance", "lifecycle", "requiredCategories", "entries", "digest"]) || catalog.schemaVersion !== "DisclosureCatalogV1" || !id.test(catalog.id) || !semver.test(catalog.version) || !id.test(catalog.owner) || (catalog.preparer !== "" && !id.test(catalog.preparer)) || catalog.owner === catalog.preparer || !array(catalog.requiredApprovals, (role) => closed(roles, role)) || catalog.requiredApprovals.length !== roles.length || !roles.every((role) => catalog.requiredApprovals.includes(role)) || catalog.provenance === undefined || !validProvenance(catalog.provenance) || !current(catalog.lifecycle, now) || !array(catalog.requiredCategories, (category) => closed(categories, category)) || !unique(catalog.requiredCategories) || !array(catalog.entries, data)) return no("policy-invalid");
  if (!await validApprovals(catalog.owner, catalog.preparer, catalog.approvals, catalog)) return no("approval-invalid");
  if (!exact(request, ["target", "binding", "instance", "requiredCategories", "consumedReplayIds", "values"]) || !exact(request.target, ["audience", "channel", "timing", "severity", "trigger", "outcome"]) || !validTarget({ ...request.target, category: categories[0] }) || !validBinding(request.binding) || !array(request.requiredCategories, (category) => closed(categories, category)) || !unique(request.requiredCategories) || request.requiredCategories.length !== catalog.requiredCategories.length || !catalog.requiredCategories.every((category, index) => request.requiredCategories[index] === category) || !array(request.consumedReplayIds, id.test.bind(id)) || !unique(request.consumedReplayIds) || !data(request.values)) return no("binding-mismatch");
  if (!(now instanceof Date) || Object.getPrototypeOf(now) !== Date.prototype || !Number.isFinite(now.getTime()) || !validInstance(request.instance, request.consumedReplayIds, now)) return no("instance-invalid");
  const ids = [catalog.id, ...catalog.entries.map((entry) => entry.id)]; if (!unique(ids)) return no("policy-invalid");
  const matching = catalog.entries.filter((entry) => data(entry.target) && data(entry.binding) && same({ ...entry.target, category: undefined }, { ...request.target, category: undefined }) && same(entry.binding, request.binding));
  const selected = request.requiredCategories.map((category) => matching.filter((entry) => entry.target.category === category)); if (selected.some((items) => items.length !== 1)) return no(selected.some((items) => items.length > 1) ? "ambiguous" : "binding-mismatch");
  const entries = selected.map((items) => items[0]!); if (entries.some((entry) => entry.conflictsWith.length > 0 || entry.ambiguous)) return no("ambiguous");
  for (const entry of entries) { if (!validEntry(entry, now) || entry.status !== "approved" || entry.supersededBy !== "") return no("entry-not-approved"); if (!await validApprovals(entry.owner, entry.preparer, entry.approvals, entry)) return no("approval-invalid"); if (!validTemplate(entry, request.values)) return no(sensitive.test(Object.values(request.values).join(" ")) ? "privacy-invalid" : "template-invalid"); }
  return { structurallyEligible: true, authority: "none", copyApproval: "not-established", entries };
} catch { return no("policy-invalid"); } }
const no = (reason: Exclude<DisclosureResolution, { structurallyEligible: true }>["reason"]): DisclosureResolution => ({ structurallyEligible: false, authority: "none", reason });
const data = (value: unknown): value is Record<string, unknown> => { if (typeof value !== "object" || value === null || Array.isArray(value) || Object.getPrototypeOf(value) !== Object.prototype) return false; const keys = Object.keys(value); const descriptors = Object.getOwnPropertyDescriptors(value); return Reflect.ownKeys(value).length === keys.length && !keys.some((key) => ["__proto__", "prototype", "constructor"].includes(key)) && keys.every((key) => descriptors[key]?.enumerable && "value" in descriptors[key]!); };
const dense = (value: unknown) => { if (!Array.isArray(value) || Object.getPrototypeOf(value) !== Array.prototype) return false; const keys = Reflect.ownKeys(value).filter((key) => key !== "length"); const descriptors = Object.getOwnPropertyDescriptors(value); return keys.length === value.length && keys.every((key, index) => key === String(index) && descriptors[String(index)]?.enumerable && "value" in descriptors[String(index)]!); };
function canonical(value: unknown, seen = new Set<object>()): string { if (value === null || typeof value === "string" || typeof value === "boolean" || (typeof value === "number" && Number.isFinite(value))) return JSON.stringify(value); if (typeof value !== "object" || seen.has(value)) throw new TypeError("non-canonical"); seen.add(value); try { if (Array.isArray(value)) { if (!dense(value)) throw new TypeError("non-canonical"); return `[${value.map((item) => canonical(item, seen)).join(",")}]`; } if (!data(value)) throw new TypeError("non-canonical"); return `{${Object.keys(value).sort().map((key) => `${JSON.stringify(key)}:${canonical(value[key], seen)}`).join(",")}}`; } finally { seen.delete(value); } }
function stripApprovals(value: unknown): unknown { if (Array.isArray(value)) { if (!dense(value)) throw new TypeError("non-canonical"); return value.map(stripApprovals); } if (value !== null && typeof value === "object") { if (!data(value)) throw new TypeError("non-canonical"); return Object.fromEntries(Object.keys(value).filter((key) => !["approvals", "subjectDigest", "signoffRef", "digest"].includes(key)).map((key) => [key, stripApprovals(value[key])])); } return value; }
async function hash(value: string) { const digest = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(value)); return [...new Uint8Array(digest)].map((byte) => byte.toString(16).padStart(2, "0")).join(""); }
